### ISSUE TITLE
Mutable methods for all data structures

### ISSUE THREAD

**Issue by orium** [orium/rpds#14]
These can use `{Rc,Arc}::make_mut()` that can speed up things a lot if there is not a lot of structural sharing.

- [x] `List`
  - [x] impl
  - [x] utests
  - [x] bench
- [x] `Vector`
  - [x] impl
  - [x] utests
  - [x] bench
- [x] `Stack`
  - [x] impl
  - [x] utests
- [x] `Queue`
  - [x] impl
  - [x] utests
- [x] `HashTrieMap`
  - [x] impl
  - [x] utests
  - [x] bench
- [x] `HashTrieSet`
  - [x] impl
  - [x] utests
- [x] `RedBlackTreeMap`
  - [x] impl
  - [x] utests
  - [x] bench
- [x] `RedBlackTreeSet`
  - [x] impl
  - [x] utests
- [x] Run clippy
- [x] Update `README.md`

**Comment by Marwes** [comment]
2c

I am not convinced about the split into mut/non-mut structures. Keeping all the methods on a single structure is both simpler to implement and easier to use. The only pro I can see for keeping it separate is that it makes it more explicit when mutating is done, however since Rust already forces the user to be explicit about mutating that is already encoded at the call site.

**Comment by orium** [comment]
My main motivation for the separation is conceptual (having neat API, separation of two different paradigms).  But I have to say that the maintenance burden of doing this separation starts to outweight the conceptual neatness I was looking for.  I will follow your suggestion and not split them.
